
const STORE = [
	"Macaroni and Cheeseburger",
    "Banana Hammock", 
    "Eight Legged Freak",
    "Lockpick Your Nose",
    "Beef Cake",
    "Lord of the Fries",
    "Pulp Nonfiction",
    "Silence of the Yams",
    "Black to the Future",
    "Spider Mantle",
    "Brave Heart Surgery",
    "Scar Face Book",
    "To Chill a Mockingbird",
    "Wolf of Mall Street",
    "Gary Potter",
    "Fox in the Box",
    "Sunnyside Up",
    "Costume Party",
    "Lipstick Figure",
    "Blackjack Hammer",
    "The Odd Father",
    "Fight or Flight Club",
    "The Lion Queen",
    "Raiders of the Lost Bark",
    "Beauty and the Yeast",
    "Singing in the Drain",
    "Internet-flix",
    "Sum Bike It Hot",
    "Pam's Labyrinth",
    "Spongebob Bear Pants",
    "Shooting Starfish",
    "Doe See Dough",
    "Tony Hawk Pro Waiter",
    "Peanut Butter Jelly Time",
    "Slip and Slide Rule",
    "Snow Day Care",
    "Smoking Breakdance",
    "Stop, Drop, and Rollerskate",
    "Fish Out of Watermelon",
    "A Website for Sore Eyes",
    "Age Before Beauty and the Beast",
    "An Apple a Daycare",
    "April Fool's Gold",
    "Happy as a Clam Chowder",
    "Back to Square Nun",
    "Mr. Quicksand Man",
    "Silver Retriever",
    "The Odyssey by Homer Simpson",
    "Chocolate Milkshake Weight",
    "Lotus P.O.T.U.S.",
    "Taco Bell Curve",
    "Rockstar and Stripes",
    "A Cough Drop in the Bucket",
    "A Foot in the Door Bell",
    "Werewolf in Sheep's Clothing",
    "Two Peas in a Podcast",
    "All That Glitters is Goldilocks",
    "As Soon as Impossible",
    "Baby Backseat Driver",
    "Beggars Can't Be Losers",
    "Belle of the Ball Game",
    "Doorbells and Whistles",
    "Blind Man's Butt",
    "Once in a Blue Moo",
    "Smokebreak a Leg",
    "Bite the Bullet Train",
    "Julius Caesar Salad",
    "Couch Potato Salad",
    "Ball Gladder",
    "Bet Your Bottom Caller",
    "Blood is Thicker than Daughter",
    "Boys Will be Toys",
    "Break the Ice Cream",
    "Bite the Mullet",
    "Cat Got Your Lung",
    "Cat Out of the Bag Boy",
    "Pajamas in Bananas",
    "Potato Chip on Your Shoulder",
    "Caught Bread-Handed",
    "Chinese Singer Trap",
    "Clock and Bull Story",
    "Book the Cooks",
    "Niel Diamond in the Rough",
    "Double Dutch Oven",
    "Elephant in the Broom",
    "Pie for an Eye",
    "Fifteen Minutes of Flame",
    "Eyeglass Ceiling",
    "Grain of Saltwater",
    "Grandmother Clock",
    "Bedhead Over Heels",
    "Heads will Bowl",
    "Heavy Metalmouth",
    "Cold Your Horses",
    "A Mouse Divided",
    "Flapjack in the Box",
    "Unjust Desserts",
    "Justin Time",
    "Man's Blessed Friend",
    "Peppermint Condition",
    "U-Turn the Other Cheek",
    "War and Peace of Cake",
    "Piggyback to Back Champions",
    "Get to the Point-Blank",
    "Snap Crackel Popcorn",
    "Hop on Pop Goes the Weasel",
    "Squid Pro Quo",
    "Rock and Roller Derby",
    "Every Nose has its Thorn",
    "Diamond in the Buff",
    "Shaved by the Belltower",
    "Shift for Brains",
    "Short End of the Sticker",
    "Oil Spill the Beans",
    "Black Swan Songbird",
    "Thinking Capstone Project",
    "Tie the Knot the Sharpest Tool",
    "Yellow-Belly Dance"
];
